import type { Job, Applicant, DashboardStats, User } from '@/types';

/**
 * Datos de prueba para desarrollo y prototipado.
 * Reemplazar con llamadas reales a la API en producción.
 */

export const MOCK_USER: User = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex.johnson@company.com',
  role: 'admin',
  department: 'Human Resources',
  avatar: undefined,
};

export const MOCK_STATS: DashboardStats = {
  activeJobs: 12,
  totalApplicants: 245,
  hiredThisMonth: 8,
  applicantsGrowthPercent: 12,
  newApplicants: 42,
  inInterview: 18,
};

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior UI/UX Designer',
    department: 'Design',
    location: 'San Francisco',
    type: 'full-time',
    status: 'active',
    applicantsCount: 42,
    newApplicantsToday: 2,
    postedDate: '2026-03-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Backend Developer',
    department: 'Engineering',
    location: 'Remote',
    type: 'remote',
    status: 'active',
    applicantsCount: 118,
    scheduledInterviews: 8,
    postedDate: '2026-03-05T00:00:00Z',
  },
  {
    id: '3',
    title: 'Product Manager',
    department: 'Product',
    location: 'New York',
    type: 'full-time',
    status: 'active',
    applicantsCount: 15,
    postedDate: '2026-03-20T00:00:00Z',
  },
];

export const MOCK_APPLICANTS: Applicant[] = [
  {
    id: 'a1',
    name: 'Alex Rivera',
    email: 'alex.rivera@email.com',
    jobId: '1',
    jobTitle: 'Senior UI/UX Designer',
    department: 'Design',
    status: 'interviewing',
    stage: 'interviewing',
    appliedDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    matchScore: 4.8,
    isOnline: true,
    lastActivityDate: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    urgency: 'interview_today',
    location: 'San Francisco, CA',
  },
  {
    id: 'a2',
    name: 'Jordan Smith',
    email: 'jordan.smith@email.com',
    jobId: '2',
    jobTitle: 'Backend Developer',
    department: 'Engineering',
    isRemote: true,
    status: 'applied',
    stage: 'applied',
    appliedDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 4.2,
    urgency: 'new_today',
    location: 'Remote',
  },
  {
    id: 'a3',
    name: 'Elena Beltrán',
    email: 'elena@email.com',
    jobId: '1',
    jobTitle: 'Senior UI/UX Designer',
    department: 'Design',
    status: 'new',
    stage: 'applied',
    appliedDate: '2026-04-01T15:00:00Z',
    matchScore: 4.5,
    location: 'Unknown',
  },
  {
    id: 'a4',
    name: 'Juan Pérez',
    email: 'juan@email.com',
    jobId: '3',
    jobTitle: 'Product Manager',
    department: 'Product',
    status: 'offered',
    stage: 'offered',
    appliedDate: '2026-03-25T10:00:00Z',
    matchScore: 4.9,
    location: 'Unknown',
  },
  {
    id: 'a5',
    name: 'Sofía Martínez',
    email: 'sofia@email.com',
    jobId: '2',
    jobTitle: 'Backend Developer',
    department: 'Engineering',
    status: 'interviewing',
    stage: 'interviewing',
    appliedDate: '2026-04-01T18:00:00Z',
    matchScore: 4.3,
    location: 'Unknown',
  },
  {
    id: 'a6',
    name: 'Marcus Chen',
    email: 'marcus.chen@email.com',
    jobId: '1',
    jobTitle: 'Senior UI/UX Designer',
    department: 'Design',
    status: 'screening',
    stage: 'screening',
    appliedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 3.9,
    urgency: 'awaiting_review',
    location: 'Palo Alto, CA',
  },
  {
    id: 'a7',
    name: 'Elena Rojas',
    email: 'elena.rojas@email.com',
    jobId: '1',
    jobTitle: 'Senior UI/UX Designer',
    department: 'Design',
    status: 'psychometric_test',
    stage: 'psychometric_test',
    appliedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 4.5,
    location: 'Austin, TX',
  },
  {
    id: 'a8',
    name: 'Julian Casablancas',
    email: 'julian.c@email.com',
    jobId: '2',
    jobTitle: 'Backend Developer',
    department: 'Engineering',
    status: 'hired',
    stage: 'hired',
    appliedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 4.9,
    location: 'New York, NY',
  },
  {
    id: 'a9',
    name: 'Sarah Connor',
    email: 's.connor@email.com',
    jobId: '3',
    jobTitle: 'Product Manager',
    department: 'Product',
    status: 'offered',
    stage: 'offered',
    appliedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 4.7,
    urgency: 'offer_pending',
    location: 'Los Angeles, CA',
  },
  {
    id: 'a10',
    name: 'Roberto Gómez',
    email: 'roberto.g@email.com',
    jobId: '2',
    jobTitle: 'Backend Developer',
    department: 'Engineering',
    status: 'selection',
    stage: 'selection',
    appliedDate: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    matchScore: 4.0,
    urgency: 'stalled',
    location: 'CDMX, MX',
  },
];

export const MOCK_INTERVIEWS = [
  {
    id: 'i1',
    applicantId: 'a1',
    applicantName: 'Alex Rivera',
    jobTitle: 'Senior UI/UX Designer',
    time: '10:00 AM',
    duration: '60 min',
    type: 'Technical Interview',
    modality: 'Video Call',
    interviewers: ['Sarah Johnson', 'Mike Chen'],
    status: 'scheduled',
  },
  {
    id: 'i2',
    applicantId: 'a6',
    applicantName: 'Marcus Chen',
    jobTitle: 'Senior UI/UX Designer',
    time: '2:00 PM',
    duration: '30 min',
    type: 'Phone Screening',
    modality: 'Voice Call',
    interviewers: ['John Doe'],
    status: 'scheduled',
  },
];
